---
claude-code: ./**/claude-code/**
flux: ./**/flux/**
flux-mcp-server: ./**/flux-mcp-server/**
github-mcp-server: ./**/github-mcp-server/**
kube-linter: ./**/kube-linter/**
kubeconform: ./**/kubeconform/**
kustomize: ./**/kustomize/**
omnictl: ./**/omnictl/**
packer: ./**/packer/**
terraform: ./**/terraform/**
terraform-mcp-server: ./**/terraform-mcp-server/**
tflint: ./**/tflint/**
