---
age: ./**/age/**
claude-code: ./**/claude-code/**
flux: ./**/flux/**
flux-mcp-server: ./**/flux-mcp-server/**
github-mcp-server: ./**/github-mcp-server/**
hcloud: ./**/hcloud/**
kube-linter: ./**/kube-linter/**
kubeconform: ./**/kubeconform/**
kustomize: ./**/kustomize/**
omnictl: ./**/omnictl/**
op: ./**/op/**
packer: ./**/packer/**
sops: ./**/sops/**
talosctl: ./**/talosctl/**
terraform: ./**/terraform/**
terraform-mcp-server: ./**/terraform-mcp-server/**
tflint: ./**/tflint/**
