---
name: features-test

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "!src/**/*.md"

jobs:
  test:
    permissions:
      pull-requests: read
    uses: bendwyer/github-workflows/.github/workflows/devcontainer-features-test.yml@main
