---
name: features-validate

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "!src/**/*.md"

jobs:
  validate:
    uses: bendwyer/github-workflows/.github/workflows/devcontainer-features-validate.yml@main
