---
name: features-release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      packages: write
    uses: bendwyer/github-workflows/.github/workflows/devcontainer-features-release.yml@main
