---
name: features-docs

on:
  pull_request:

jobs:
  docs:
    uses: bendwyer/github-workflows/.github/workflows/devcontainer-features-documentation.yml@change-docs-generation-trigger
    with:
      gh_app_id: ${{ vars.GH_APP_ID }}
    secrets:
      gh_app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
