---
name: features-test

on:
  pull_request:

jobs:
  test:
    permissions:
      pull-requests: read
    uses: bendwyer/github-workflows/.github/workflows/devcontainer-features-test.yml@add-devcontainer-feature-workflows
    with:
      filter_file_path: ./.github/filters.yml
